
// TASK #1
const randomNumber = Math.random(); // produces random number between 0 (including) and 1 (excluding)

function generateMessage(numGreaterthan7){
  if(numGreaterthan7 > 0.7){
    alert('This message was generated by a function.');
    console.log(numGreaterthan7);
  }else{
    console.log(numGreaterthan7);
   return;
  }
}
generateMessage(randomNumber);

// TASK #2 
const Numbers =[1,2,3,4,5];

console.log('-----------LOOP 1-------------');

for(let index = 0; index < 5; index++){
    console.log(Numbers[index]);
}

console.log('-----------LOOP 2-------------');
for(let index = 0; index < Numbers.length; index++){
    console.log(Numbers[index]);
}

// TASK #3
console.log('-----------REVERSE LOOP-------------');
for(let index = Numbers.length - 1; index >= 0; index--){
    console.log(Numbers[index]);
}

// TASK #4 
const randomInteger = Math.random();


function writeMessage(Permission1, Permission2){
    if(Permission1 > 0.7 && Permission2 > 0.7){
      alert('Permission granted, Welcome to the CyberSpace ');
      console.log(Permission1,Permission2);
    }else if(Permission1 > .2  || Permission2 > .2){
      alert('Either one of the permission is granted, Welcome you are halfway succesfull to login.');
      console.log(Permission1,Permission2);
    }else{
      return;
    }
}

writeMessage(randomNumber, randomInteger);